name: Tests
on:
  push:
    paths: '**.luau'
    branches: 'main'
  pull_request:
    paths: '**.luau'
  workflow_dispatch:
    
jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        module: [sha1, sha256, sha224, sha512, sha384, xxhash32, blake2s]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Install Luau'
        run: |
          gh release download --repo Roblox/luau --pattern luau-ubuntu.zip
          unzip luau-ubuntu.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 'Test'
        run: ./luau tests/${{ matrix.module}}.luau

      - name: 'Test (Codegen)'
        run: ./luau tests/${{ matrix.module}}.luau --codegen